### ISSUE TITLE
Error when executing "terrainBlockMesher

### ISSUE THREAD

**Issue by EloneSampaio** [jonasIWES/terrainBlockMesher#6]
Greetings, thank you in advance for creating this incredible tool.

 Contextualizing

I did the installation following the installation guide but when I will run the example "iwesol/OF-2.1.1/tutorials/utilities/mesh/terrainBlockMesher" 

Give me the following error message:
"terrainBlockMesher: error while loading shared libraries: libolCppIO.so: cannot open shared object file: No such file or directory"

I have searched all the forums and found nothing to solve this situation. 

My Openfoam installation is 2.3.1 and it works normally.

Translated with www.DeepL.com/Translator (free version)

**Comment by SchmJo** [comment]
It looks like it did not find one of the libraries - did you source OF231? If so, please check if the .so file exists in $FOAM_USER_LIBBIN.

**Comment by EloneSampaio** [comment]
I managed to solve the problem. 
For those who find the same problem they need to copy the files from the directory "/terrainBlockMesher/iwesol/nonOF/c++/lib". to the directory 
$FOAM_USER_LIBBIN
and be happy...

Sam
